name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: "echo TODO: docker build . --file Dockerfile --tag jojojonek/tabris-js-build-android:$(date +%s)"
    - name: Secret example
      env:
        FOO: {{ secrets.FOO }}
      run: "echo The FOO secret is '${FOO}'!"
    - name: Publish to Docker Hub
      env:
        DOCKERHUB_USERNAME: {{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: {{ secrets.DOCKERHUB_PASSWORD }}
      run: docker login --username ${DOCKERHUB_USERNAME} --password ${DOCKERHUB_PASSWORD}
    - name: Logout from Docker Hub
      run: docker logout
